import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const PLUGIN_PATH = "D:\\WS2\\plug-in\\.obsidian\\plugins\\card";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: prod ? "build/main.js" : "main.js",
	minify: prod,
	platform: "node",
	jsx: "automatic",
	jsxImportSource: "preact",
	alias: {
		"react": "preact/compat",
		"react-dom": "preact/compat"
	}
});

// 빌드 후 파일 복사 함수
function copyFilesToBuild() {
	// build 폴더 생성
	if (!existsSync("build")) {
		mkdirSync("build");
	}

	// manifest.json 복사
	if (existsSync("manifest.json")) {
		copyFileSync("manifest.json", "build/manifest.json");
	}

	// styles.css 복사
	if (existsSync("styles.css")) {
		copyFileSync("styles.css", "build/styles.css");
	}
}

// 플러그인 폴더로 파일 복사 함수
function copyToPluginFolder() {
	// 플러그인 폴더가 없으면 생성
	if (!existsSync(PLUGIN_PATH)) {
		mkdirSync(PLUGIN_PATH, { recursive: true });
	}

	// build 폴더의 모든 파일을 플러그인 폴더로 복사
	const filesToCopy = ["main.js", "manifest.json", "styles.css"];
	
	filesToCopy.forEach(file => {
		const sourcePath = `build/${file}`;
		const targetPath = `${PLUGIN_PATH}/${file}`;
		
		if (existsSync(sourcePath)) {
			copyFileSync(sourcePath, targetPath);
		}
	});
}

if (prod) {
	await context.rebuild();
	copyFilesToBuild();
	copyToPluginFolder();
	process.exit(0);
} else {
	await context.watch();
}
